version: '2'

services:
  database:
    container_name: database-producao
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3308
      - 33080:33080
    expose:
      - 3308
      - 33080
    environment:
      MYSQL_DATABASE: producao
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_TCP_PORT: 3308
    volumes:
      - /var/local/fiap-producao/mysql:/var/lib/mysql