spring:
  datasource:
    url: jdbc:mysql://localhost:3308/producao
    username: root
    password: senha
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true
